### ISSUE TITLE
Support v4 of the AWS provider

### ISSUE THREAD

**Issue by sarahhodne** [lacework/terraform-aws-iam-role#26]
# Feature Request

**Describe the Feature Request**

This module depends on the AWS provider using `~> 3.0`, so it's not compatible with a module using v4.

It looks like the only things from the AWS provider used are the `aws_iam_role` resource and `aws_iam_policy_document` data source, in ways that appear unaffected according to the [upgrade guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade) and [release notes](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.0.0), so hopefully adding support should be as easy as loosening the version constraint.

**Is your feature request related to a problem? Please describe**

Cannot upgrade to v4 of the AWS provider while using this module.

**Describe Preferred Solution**

The module is declared to support v4 of the provider, perhaps with `>= 3.0, < 5.0` or something similar.

**Additional Context**

- AWS provider v4 upgrade guide: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade
- AWS provider 4.0.0 release notes: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.0.0

**Comment by afiune** [comment]
Hello @sarahhodne 👋🏽  - Thank you for your feedback, we are going to include this feature request into our next sprint planning and prioritize it accordingly, as a heads up, we just did this for the Google provider so we should be able to tackle this fast.

We will update this issue with any progress we make. 🙌🏽 

Jira: https://lacework.atlassian.net/browse/ALLY-881
